name: Build One Extension

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #   - name: Cache
    #     uses: actions/cache@v4.2.3
    #     with:
    # # A list of files, directories, and wildcard patterns to cache and restore
    #       path: ""
    # # An explicit key for restoring and saving the cache
    #       key: ""
    # # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build selected extension
        run: |
          # Replace this with the actual module path, e.g., :src:en:mangadex
          ./gradlew :src:en:kaido:assembleDebug

      - name: Find APK
        run: |
          find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-debug-apk
          path: "**/*.apk"

